// reverse mapping for string values enum members does not work in Typescript, so names === codes
export enum Currency {
  EUR = 'EUR', // 978	Euro
  AUD = 'AUD', // 036	Dollaro Australiano
  CAD = 'CAD', // 124	Dollaro Canadese
  HKD = 'HKD', // 344	Dollaro di Hong Kong
  JPY = 'JPY', // 392	Yen Giapponese
  CHF = 'CHF', // 756	Franco Svizzero
  GBP = 'GBP', // 826	Sterlina
  USD = 'USD', // 840	Dollaro Americano
  BRL = 'BRL', // 986	Real Brasiliano
  SGD = 'SGD', // 702	Dollaro di Singapore
  AED = 'AED', // 784	Dirham degli Emirati Arabi Uniti
  TWD = 'TWD', // 901	Dollaro Taiwanese
  SAR = 'SAR', // 682	Riyal Saudita
  IDR = 'IDR', // 360	Rupiah Indonesiana
  THB = 'THB', // 764	Baht Thailandese
  KWD = 'KWD', // 414	Dinaro Kuwaitiano
  MYR = 'MYR', // 458	Ringgit Malese
  QAR = 'QAR', // 634	Riyal del Qatar
  MXN = 'MXN', // 484	Peso Messicano
  ZAR = 'ZAR', // 710	Rand Sudafricano
  KRW = 'KRW', // 410	Won Sudcoreano
  PLN = 'PLN', // 985	Złoty polacco
  INR = 'INR', // 356	Rupia indiana
  PHP = 'PHP', // 608	Peso Filippino
  CZK = 'CZK', // 203	Corona Ceca
  NZD = 'NZD', // 554	Dollaro Neo Zelandese
  CLP = 'CLP', // 152	Peso Cileno
  RON = 'RON', // 946	Leu Romeno
  HUF = 'HUF', // 348	Fiorino Ungherese
  COP = 'COP', // 170	Peso Colombiano
  BHD = 'BHD', // 048	Dinaro del Bahrein
  EGP = 'EGP', // 818	Sterlina Egiziana
  HRK = 'HRK', // 191	Kuna Croata
  VEF = 'VEF', // 862	Bolívar venezuelano
  JOD = 'JOD', // 400	Dinaro Giordano
  ARS = 'ARS', // 032	Peso Argentino
  MOP = 'MOP', // 446	Pataca di Macao
  DKK = 'DKK', // 208	Corona Danese
  SEK = 'SEK' // 752	Corona Svedese
}
